<?php


class Controller_Achievement extends Controller
{
    public $error = array();
    public $message = array();
    public $db;
    public $host;


    public function __construct()
    {
        $this->model = new Model_Achievement();
        $this->view = new View();
        $this->db = $this->model->db;
        $this->UID = $_SESSION['login'];
        $this->host = 'http://'.$_SERVER['HTTP_HOST'].'/';
    }

    public function action_index()
    {
        parent::action_index(); // TODO: Change the autogenerated stub
    }

    public function action_area($id=null){
        if($this->UID == null){
            header('Location: http://'.$_SERVER['HTTP_HOST'].'/');
        }
        $data = $this->model->get_achievement($id);
        if(!empty($data)) {
            $this->view->generate('achievement_view.php', 'template_view.php', $data, $this->UID);
        }else{
            header('Location:'.$this->host.'404');
        }
    }


}