<?php


class Controller_Achievement extends Controller
{
    public $error = array();
    public $message = array();
    public $db;
    public $areaName;
    public $areaDescription;
    public $start_date;

    public function __construct()
    {
        $this->model = new Model_Achievement();
        $this->view = new View();
        $this->db = $this->model->db;
        $this->UID = $_SESSION['login'];
    }

    public function action_index()
    {
        parent::action_index(); // TODO: Change the autogenerated stub
    }

    public function action_area($id){
        if($this->UID == null){
            header('Location: http://'.$_SERVER['HTTP_HOST'].'/');
        }
        $data = $this->model->get_achievement($id);
        $this->view->generate('achievement_view.php', 'template_view.php', $data, $this->UID);
    }


}